import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { GridCard } from '../components/GridCard'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ChemE Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        {/* <div className="absolute -z-10 h-screen w-screen ">
          <Image src="/triangleBackground.png" layout="fill" objectFit="cover" quality={100} />
        </div> */}
        <h1 className="text-5xl font-extrabold leading-normal text-neutral-focus md:text-[5rem]">
          Chem<span className="text-accent">E</span> Calculator
        </h1>
        <div className="my-3 grid gap-9 py-3 text-center md:grid-cols-3 lg:w-2/3">
          <GridCard name="Fluid Flow" description="Calculators for fluid dynamics" link="/fluidflow" />
          <GridCard name="Heat Transfer" description="Calculators for thermodynamics" link="/heattransfer" />
          <GridCard name="Geometry" description="Calculators for geometric properties" link="/geometry" />
        </div>
      </main>
    </>
  )
}

export default Home
