import type { NextPage } from "next";
import Head from "next/head";
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ChemE Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal md:text-[5rem] text-neutral-focus">
          Chem<span className="text-accent">E</span> Calculator
        </h1>
        <div className="my-3 grid gap-9 py-3 text-center md:grid-cols-3 lg:w-2/3">
          <CalcCard
            name="Fluid Flow"
            description="Calculators for fluid dynamics"
            link="/fluidflow"
          />
          <CalcCard
            name="Heat Transfer"
            description="Calculators for thermodynamics"
            link="/heattransfer"
          />
          <CalcCard
            name="Geomentry"
            description="Calculators for geometric properties"
            link="/geometry"
          />
        </div>
      </main>
    </>
  );
};

export default Home;

type CalcCardProps = {
  name: string;
  description: string;
  link: string;
};

const CalcCard = ({
  name,
  description,
  link,
}: CalcCardProps) => {
  return (
    <Link href={link}>
    <section className="card w-56 shadow-nuetral shadow-2xl motion-safe:hover:scale-105 duration-500 cursor-pointer bg-base-300-content text-base-content">
    <div className="card-body">
      <h2 className="card-title justify-center ">{name}</h2>
      <p>{description}</p>
    </div>
  </section>
        </Link>
  );
};
