import type { NextPage } from "next";
import Head from "next/head";
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ChemE Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-base md:text-[5rem] text-primary">
          Chem<span className="text-secondary">E</span> Calculator
        </h1>
        <div className="mt-3 grid gap-3 pt-3 text-center md:grid-cols-3 lg:w-2/3">
          <CalcCard
            name="Fluid Flow"
            description="Calculators for fluid dynamics"
            link="/fluidflow"
          />
          <CalcCard
            name="Heat Transfer"
            description="Calculators for thermodynamics"
            link="/heattransfer"
          />
          <CalcCard
            name="Equipment"
            description="Calculators for equipment properties"
            link="/equipment"
          />
        </div>
      </main>
    </>
  );
};

export default Home;

type CalcCardProps = {
  name: string;
  description: string;
  link: string;
};

const CalcCard = ({
  name,
  description,
  link,
}: CalcCardProps) => {
  return (
    <Link href={link}>
    <section className="flex flex-col justify-center rounded border-2 border-primary p-6 shadow-xl duration-500 motion-safe:hover:scale-105 cursor-pointer" >
      <h2 className="text-lg text-primary">{name}</h2>
      <p className="text-sm text-secondary">{description}</p>
    </section>
        </Link>
  );
};
